### ISSUE TITLE
Thanks for this!! :D

### ISSUE THREAD

**Issue by NHDaly** [jonathanBieler/SDL2.jl#1]
Hi! This isn't really an "issue," I just wasn't sure where the best place to say *thank you!* is. :)

So thanks for this fun package! I cloned it like a month ago, and built a complete, working game with it!! :D  
I'm going to share the source for that on github soon. But first, I stupidly was working heads-down on the game and didn't ever check to see if this package had been updated.. And in the process of working on the game, I made a couple of my own changes, including adding in SDL2_mixer. :)

So I want to try to move my game over to the latest HEAD for this repo before pushing the code, otherwise it'd be useless. But yeah, just wanted to say thanks!! Writing this game was _so easy_. SDL is already a fun, straightforward library, (and it brings back some nostalgia to my early programming days), but doing it in `julia` instead of `c++` was even better. :]

**Comment by jonathanBieler** [comment]
Hey no problem, I haven't done much to be honest, I just ran Clang.jl wrapper and clean up a bit the mess. It would be good to add some documentation, tests and stuff and release it though.
